# Generated by Django 5.1.6 on 2025-05-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estancia_producto_estancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
